set_property PACKAGE_PIN G5 [get_ports clk]
set_property PACKAGE_PIN G6 [get_ports i]
set_property PACKAGE_PIN F6 [get_ports j]
set_property PACKAGE_PIN G7 [get_ports o]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports i]
set_property IOSTANDARD LVCMOS18 [get_ports j]
set_property IOSTANDARD LVCMOS18 [get_ports o]
